// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ArenDjango/golang-test-task/model"
	mock "github.com/stretchr/testify/mock"
)

// RatesService is an autogenerated mock type for the RatesService type
type RatesService struct {
	mock.Mock
}

// GetRates provides a mock function with given fields: _a0, _a1
func (_m *RatesService) GetRates(_a0 context.Context, _a1 string) (*model.Rates, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetRates")
	}

	var r0 *model.Rates
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Rates, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Rates); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Rates)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRatesService creates a new instance of RatesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRatesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RatesService {
	mock := &RatesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
